name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        gradle-version: '8.13'

    - name: Generate Gradle Wrapper
      run: |
        if [ ! -f ./gradlew ]; then
          gradle wrapper --gradle-version 8.13
        fi
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # - name: Run Lint
    #   run: ./gradlew lint

    # - name: Run Unit Tests
    #   run: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Create Tag
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        TAG_NAME="v${{ github.run_number }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
        name: Automated Build ${{ github.sha }}
        tag_name: v${{ github.run_number }}
        body: |
          Automated build from commit ${{ github.sha }}
          Build date: ${{ github.event.head_commit.timestamp }}
